# Site settings
title: testify
email: your-email@domain.com
url: https://marvlm.github.io/testify
description: "Y nosotros hemos visto y testificamos que el Padre ha enviado al Hijo, el Salvador del mundo. <br/> <br/> <b>1 Juan 4:14</b> <br/> <br/>Jesus hizo muchas otras señales milagrosas en presencia de sus discípulos... <br/> <br/> <b>Juan 20:30</b><br/>"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
